apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend # just name for virtualservice
spec:
  hosts:
    - backend # service name to call
  http:
    - match:
        - headers:
            kubeds:
              exact: enabled
      route:
        - destination:
            host: backend
            subset: v2
    - route:
        - destination:
            host: backend # service name to call
            subset: v1 # name for subset name
